### ISSUE TITLE
aarddict's function invoked through command line are broken

### ISSUE THREAD

**Issue by itkach** [aarddict/desktop#16]
Invoking aarddict on the command line with --verify, --identify or --metadata options results in errors:

```
$ aarddict -v ~/Downloads/wordnet-3.0-1.html.aar 
Traceback (most recent call last):
  File "/home/itkach/env-aard/bin/aarddict", line 9, in <module>
    load_entry_point('aarddict==0.9.1.dev', 'gui_scripts', 'aarddict')()
  File "/home/itkach/env-aard/aarddict/aarddict/__init__.py", line 97, in main
    d = dictionary.Dictionary(file_name)
AttributeError: 'module' object has no attribute 'Dictionary'

$ aarddict -i ~/Downloads/wordnet-3.0-1.html.aar 
/home/itkach/Downloads/wordnet-3.0-1.html.aar:
Traceback (most recent call last):
  File "/home/itkach/env-aard/bin/aarddict", line 9, in <module>
    load_entry_point('aarddict==0.9.1.dev', 'gui_scripts', 'aarddict')()
  File "/home/itkach/env-aard/aarddict/aarddict/__init__.py", line 80, in main
    header = dictionary.Header(f)
AttributeError: 'module' object has no attribute 'Header'

$ aarddict -m ~/Downloads/wordnet-3.0-1.html.aar 
Traceback (most recent call last):
  File "/home/itkach/env-aard/bin/aarddict", line 9, in <module>
    load_entry_point('aarddict==0.9.1.dev', 'gui_scripts', 'aarddict')()
  File "/home/itkach/env-aard/aarddict/aarddict/__init__.py", line 119, in main
    d = dictionary.Dictionary(file_name)
AttributeError: 'module' object has no attribute 'Dictionary'
```

**Comment by itkach** [comment]
Fixed in e6f4a74464cc93af38a6876a93584d8e324ac4cd
